# Generated by Django 2.2.7 on 2019-11-29 13:42

from django.db import migrations, models
import pitter.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('pitter', '0002_auto_20191123_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='follower',
            name='id',
            field=models.CharField(default=pitter.models.base.default_uuid_id, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
