# Generated by Django 2.2.7 on 2019-12-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitter', '0003_auto_20191129_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitt',
            name='speech_audio_file',
        ),
        migrations.AddField(
            model_name='pitt',
            name='speech_audio_file_path',
            field=models.CharField(default='audio.wav', max_length=512),
            preserve_default=False,
        ),
    ]
